== Referenced standards

RISC-V Unified Discovery builds on the X.680-X.693 ("Information Technology - Abstract Syntax Notation One (ASN.1) & ASN.1 encoding rules" standards-series published by the International Telecommunications Union (ITU):

. X.680: Information technology - Abstract Syntax Notation One (ASN.1): Specification of basic notation https://www.itu.int/rec/T-REC-X.680/en
. X.681: Information technology - Abstract Syntax Notation One (ASN.1): Information object specification
. X.682: Information technology - Abstract Syntax Notation One (ASN.1): Constraint specification
. X.683: Information technology - Abstract Syntax Notation One (ASN.1): Parameterization of ASN.1 specifications
. X.690: Information technology - ASN.1 encoding rules: Specification of Basic Encoding Rules (BER), Canonical Encoding Rules (CER) and Distinguished Encoding Rules (DER) https://www.itu.int/rec/T-REC-X.690/en[Link]
. X.691: Information technology - ASN.1 encoding rules: Specification of Packed Encoding Rules (PER) https://www.itu.int/rec/T-REC-X.691/en[Link]

The X.680-X.693 standards are well-established, openly-available standards that are proven building blocks for a wide variety of information technology applications, including X.509 digital certificates, SNMP, LDAP, ISO 7816-4 smartcards, 4G/LTE, and 5G.
