:version: 0.1.0
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:toc: left

= RISC-V Configuration Description Version {version}

Contributors to all versions of the spec in alphabetical order (please
contact editors to suggest corrections): TODO

== Preface

*Warning! This draft specification will change before being accepted as
standard, so implementations made to this draft specification will
likely not conform to the future standard.*

== Rational

It is generally useful for software to be able to programmatically
determine the capabilities of the hardware it is running on. The
software needs the information to discover the core and hart feature
availability for executing the different initialization code paths,
particularly when the software runs on a socketed system that supports
the pluggable cores. External
debuggers need to know the same information. RISC-V extensions mostly
use CSRs for this information, but that is not flexible enough for some
kinds of data like hardware breakpoint capabilities, and cache
hierarchy.

This document specifies syntax, semantics, discovery method, and access
method for a static data structure that can accommodate implementation
parameters of RISC-V standards beyond what can be easily put into CSRs.
The structure is called a Configuration Structure (CS).

== Representation of Configuration Structure 

=== Schema of Configuration Structure

The schema of Configuration Structure is the data structure that declares
the data format which can be used to describe the configuration of core
and hart features. Configuration Structure is typically grouping base on the extension.
The schema allows to support the next generation of extensions and OEM
extensions, however still backward compatible with the previous versions of
extensions.

To accommodate minimal on-chip descriptions on small systems, and larger
descriptions for other use cases implementation decisions are divided into
the following three categories:

1. ((Primary)) information is only discoverable by reading the configuration
structure, or by running a significant amount of code. Examples: the number of
hardware triggers supported, ...
2. ((Secondary)) information is discoverable but not straightforward (e.g. WARL
register). Examples: whether the F extension is supported, ...
3. Anything else goes in the ((Complete)) section. Examples: the value of XLEN,
...

=== Contents of Configuration Structure

The Configuration Structure contains a static description of a hardware
platform. The static descriptions are the values that made follow the
schema of Configuration Structure. It describes, in varying levels of detail, the
implementation decisions made by the hardware designer. The description is
static and is not affected by the current state of the system.

==== Human-Readable Format

ASN.1 defines a value syntax, but it's not well-supported among open source
solutions. For now we propose using https://www.itu.int/rec/T-REC-X.697/en[ASN.1
((JER))], which is a JSON representation of the ASN.1 value.

In the future, we should be able to accept YAML with little extra work, and the
big immediate benefit of a format that supports comments.

==== Machine-Readable Format

A binary-encoded representation of a conﬁguration is made available to software
that is running on the system.
The Human-readable format is encoded to the binary using the standardized
unaligned packed encoding rules (unaligned PER,
see https://www.itu.int/rec/T-REC-X.691/en[ASN.1 ((UPER))], which is very compact.

== Use Cases

=== System Firmware

Typical system firmware is executed when the system is powered on. It
initializes hardware and builds up firmware services or data structures
for booting up the system to OS. Examples are uboot for embedded
systems and BIOS (majority firmware solution is UEFI TianoCore) for PCs
and servers, or other firmware framwworks.

Through a combination of checking CSRs and accessing the system
description, firmware can
programmatically determine the hardware capabilities and configure
hardware accordingly. These hardware capabilities can include
availability and implemented features of Physical Memory Protection
(PMP), Core Local Interrupt Controller (CLIC), Core Local Interruptor
(CLINT), memory map, virtual memory, Trusted Execution Environment
(TEE), and any future optional core and hart features.

The Configuration Structure is an efficient alternative to testing for
specific hardware features (including handling failures) or customizing
system firmware for the specific system it will run on.

Often system firmware will take the information it has learned from the
system description as well as through other methods, and encode it into
a different industry-standard data structure (like Devicetree, SMBIOS and
ACPI). This structure is then passed to the subsequent boot process.

=== External Debuggers

When an external debugger connects to a system, it would like to
discover as much as possible about that system in as little time as
possible. Some of this is merely to show the user (e.g. a manufacturer
name), while other features are critical to the user (e.g. XLEN), and
other features determine what kind of operations the user can perform
(e.g. supported hardware trigger types). Most of these are already
discoverable, although many require writing a value and checking the
result to see whether support exists.

Any structure that’s accessible from M-mode software will already be
accessible by the debugger. There might be a structure embedded in the
Debug Module itself which is only accessible by the debugger.

The debug feature that is most complex to describe is hardware triggers.
Each hart may have billions of triggers (although 4 is more typical).
Each of those triggers can be one of 4 types, and each type has its own
options. Options are things like trigger on execute/load/store, in M/S/U
mode, chain to other trigger, exact/greater/less-than value match, etc.
It’s permissible for features to be implemented, but not in all
combinations. E.g. greater value might work in combination with
load/store, but not together with executed. Each trigger is configured
by writing an XLEN-bit register.

In addition there are abstract commands, which have similar issues.
There are a few commands, with a number of options.

=== Off-line Development Tools

A lot of development happens without access to the hardware, and software as
well as hardware development tools can benefit from having a standardized
description of hardware features to work from.

[[sec:AccessMethod]]
== Access Method to Machine-Readable Format

The binary configuration structure is memory-mapped in system memory.
mconfigptr contains the physical address where the structure starts.
When software running on a hart wants to read the configuration structure, it
reads mconfigptr, and then decodes the binary structure at that physical address.
The structure will specify which parts apply to which harts (identified by hart
ID), and the software can ignore any information that does not apply to the hart
it's running on.

image::resources/images/mconfigptr.svg[Access Method to Applications]

=== Implementation Examples

There are several options for embedding the binary structure:

1. The structure can describe all harts, and be accessible over the memory bus.
All harts have the same memory map and the same value in mconfigptr.
2. There might be several structures in the system, and different harts are
pointed to different structures by having different pointers in mconfigptr.
3. There might be several structures in the system. Each hart has the same
address in mconfigptr. The memory system provides a different configuration
structure at that address depending on which hart is performing the access.
4. A combination of 2 and 3 above could be used.

Hardware implementers have a lot of flexibility to handle everything from simple
fixed systems to complex socketed systems. In each case it's straightforward to
ensure that each hart can read a configuration structure that describes its own
capabilities.

[[sec:ExternalIndustrialStandard]]
== External Industrial Standards

https://www.devicetree.org/specifications/[DeviceTree v0.3] +
https://uefi.org/specifications[ACPI v6.3] +
https://www.dmtf.org/standards/smbios[SMBIOS v3.5.0] +
https://github.com/riscv/riscv-smbios/blob/master/riscv-smbios.adoc[RISC-V SMBIOS Type 44H]
