/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "AbstractCommand.h"

static asn_TYPE_member_t asn_MBR_accessRegister_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccessRegisterCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_accessRegister_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_accessRegister_specs_2 = {
	sizeof(struct accessRegister),
	offsetof(struct accessRegister, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_accessRegister_2 = {
	"accessRegister",
	"accessRegister",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_accessRegister_tags_2,
	sizeof(asn_DEF_accessRegister_tags_2)
		/sizeof(asn_DEF_accessRegister_tags_2[0]) - 1, /* 1 */
	asn_DEF_accessRegister_tags_2,	/* Same as above */
	sizeof(asn_DEF_accessRegister_tags_2)
		/sizeof(asn_DEF_accessRegister_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_accessRegister_2,
	1,	/* Single element */
	&asn_SPC_accessRegister_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_quickAccess_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_quickAccess_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_quickAccess_specs_4 = {
	sizeof(struct quickAccess),
	offsetof(struct quickAccess, _asn_ctx),
	1,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_quickAccess_4 = {
	"quickAccess",
	"quickAccess",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_quickAccess_tags_4,
	sizeof(asn_DEF_quickAccess_tags_4)
		/sizeof(asn_DEF_quickAccess_tags_4[0]) - 1, /* 1 */
	asn_DEF_quickAccess_tags_4,	/* Same as above */
	sizeof(asn_DEF_quickAccess_tags_4)
		/sizeof(asn_DEF_quickAccess_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_quickAccess_4,
	1,	/* Single element */
	&asn_SPC_quickAccess_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_accessMemory_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccessMemoryCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_accessMemory_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_accessMemory_specs_6 = {
	sizeof(struct accessMemory),
	offsetof(struct accessMemory, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_accessMemory_6 = {
	"accessMemory",
	"accessMemory",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_accessMemory_tags_6,
	sizeof(asn_DEF_accessMemory_tags_6)
		/sizeof(asn_DEF_accessMemory_tags_6[0]) - 1, /* 1 */
	asn_DEF_accessMemory_tags_6,	/* Same as above */
	sizeof(asn_DEF_accessMemory_tags_6)
		/sizeof(asn_DEF_accessMemory_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_accessMemory_6,
	1,	/* Single element */
	&asn_SPC_accessMemory_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AbstractCommand_1[] = {
	{ ATF_POINTER, 3, offsetof(struct AbstractCommand, accessRegister),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_accessRegister_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"accessRegister"
		},
	{ ATF_POINTER, 2, offsetof(struct AbstractCommand, quickAccess),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_quickAccess_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"quickAccess"
		},
	{ ATF_POINTER, 1, offsetof(struct AbstractCommand, accessMemory),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_accessMemory_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"accessMemory"
		},
};
static const int asn_MAP_AbstractCommand_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_AbstractCommand_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AbstractCommand_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* accessRegister */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* quickAccess */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* accessMemory */
};
asn_SEQUENCE_specifics_t asn_SPC_AbstractCommand_specs_1 = {
	sizeof(struct AbstractCommand),
	offsetof(struct AbstractCommand, _asn_ctx),
	asn_MAP_AbstractCommand_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_AbstractCommand_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AbstractCommand = {
	"AbstractCommand",
	"AbstractCommand",
	&asn_OP_SEQUENCE,
	asn_DEF_AbstractCommand_tags_1,
	sizeof(asn_DEF_AbstractCommand_tags_1)
		/sizeof(asn_DEF_AbstractCommand_tags_1[0]), /* 1 */
	asn_DEF_AbstractCommand_tags_1,	/* Same as above */
	sizeof(asn_DEF_AbstractCommand_tags_1)
		/sizeof(asn_DEF_AbstractCommand_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AbstractCommand_1,
	3,	/* Elements count */
	&asn_SPC_AbstractCommand_specs_1	/* Additional specs */
};

