/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "Configuration.h"

static asn_TYPE_member_t asn_MBR_harts_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Hart,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_harts_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_harts_specs_2 = {
	sizeof(struct harts),
	offsetof(struct harts, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_harts_2 = {
	"harts",
	"harts",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_harts_tags_2,
	sizeof(asn_DEF_harts_tags_2)
		/sizeof(asn_DEF_harts_tags_2[0]) - 1, /* 1 */
	asn_DEF_harts_tags_2,	/* Same as above */
	sizeof(asn_DEF_harts_tags_2)
		/sizeof(asn_DEF_harts_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_harts_2,
	1,	/* Single element */
	&asn_SPC_harts_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_debugModule_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DebugModule,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_debugModule_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_debugModule_specs_4 = {
	sizeof(struct debugModule),
	offsetof(struct debugModule, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_debugModule_4 = {
	"debugModule",
	"debugModule",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_debugModule_tags_4,
	sizeof(asn_DEF_debugModule_tags_4)
		/sizeof(asn_DEF_debugModule_tags_4[0]) - 1, /* 1 */
	asn_DEF_debugModule_tags_4,	/* Same as above */
	sizeof(asn_DEF_debugModule_tags_4)
		/sizeof(asn_DEF_debugModule_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_debugModule_4,
	1,	/* Single element */
	&asn_SPC_debugModule_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_physicalMemory_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PhysicalMemory,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_physicalMemory_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_physicalMemory_specs_7 = {
	sizeof(struct physicalMemory),
	offsetof(struct physicalMemory, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_physicalMemory_7 = {
	"physicalMemory",
	"physicalMemory",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_physicalMemory_tags_7,
	sizeof(asn_DEF_physicalMemory_tags_7)
		/sizeof(asn_DEF_physicalMemory_tags_7[0]) - 1, /* 1 */
	asn_DEF_physicalMemory_tags_7,	/* Same as above */
	sizeof(asn_DEF_physicalMemory_tags_7)
		/sizeof(asn_DEF_physicalMemory_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_physicalMemory_7,
	1,	/* Single element */
	&asn_SPC_physicalMemory_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Configuration_1[] = {
	{ ATF_POINTER, 4, offsetof(struct Configuration, harts),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_harts_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"harts"
		},
	{ ATF_POINTER, 3, offsetof(struct Configuration, debugModule),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_debugModule_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"debugModule"
		},
	{ ATF_POINTER, 2, offsetof(struct Configuration, traceModule),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceModule,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"traceModule"
		},
	{ ATF_POINTER, 1, offsetof(struct Configuration, physicalMemory),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_physicalMemory_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"physicalMemory"
		},
};
static const int asn_MAP_Configuration_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_Configuration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Configuration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* harts */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* debugModule */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* traceModule */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* physicalMemory */
};
static asn_SEQUENCE_specifics_t asn_SPC_Configuration_specs_1 = {
	sizeof(struct Configuration),
	offsetof(struct Configuration, _asn_ctx),
	asn_MAP_Configuration_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Configuration_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Configuration = {
	"Configuration",
	"Configuration",
	&asn_OP_SEQUENCE,
	asn_DEF_Configuration_tags_1,
	sizeof(asn_DEF_Configuration_tags_1)
		/sizeof(asn_DEF_Configuration_tags_1[0]), /* 1 */
	asn_DEF_Configuration_tags_1,	/* Same as above */
	sizeof(asn_DEF_Configuration_tags_1)
		/sizeof(asn_DEF_Configuration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Configuration_1,
	4,	/* Elements count */
	&asn_SPC_Configuration_specs_1	/* Additional specs */
};

