/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#ifndef	_DebugModule_H_
#define	_DebugModule_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AbstractCommand;
struct FlexibleRange;

/* DebugModule */
typedef struct DebugModule {
	long	*index	/* OPTIONAL */;
	struct AbstractCommand	*abstract	/* OPTIONAL */;
	struct FlexibleRange	*connectedHarts	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DebugModule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DebugModule;
extern asn_SEQUENCE_specifics_t asn_SPC_DebugModule_specs_1;
extern asn_TYPE_member_t asn_MBR_DebugModule_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AbstractCommand.h"
#include "FlexibleRange.h"

#endif	/* _DebugModule_H_ */
#include <asn_internal.h>
