/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#ifndef	_DebugTrigger_H_
#define	_DebugTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FlexibleRange.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DebugTriggerMcontrol;
struct DebugTriggerMcontrolCompact;

/* DebugTrigger */
typedef struct DebugTrigger {
	FlexibleRange_t	 index;
	struct mcontrol {
		A_SEQUENCE_OF(struct DebugTriggerMcontrol) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mcontrol;
	struct mcontrolcompact {
		A_SEQUENCE_OF(struct DebugTriggerMcontrolCompact) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mcontrolcompact;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DebugTrigger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DebugTrigger;
extern asn_SEQUENCE_specifics_t asn_SPC_DebugTrigger_specs_1;
extern asn_TYPE_member_t asn_MBR_DebugTrigger_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DebugTriggerMcontrol.h"
#include "DebugTriggerMcontrolCompact.h"

#endif	/* _DebugTrigger_H_ */
#include <asn_internal.h>
