/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "DebugTrigger.h"

static asn_TYPE_member_t asn_MBR_mcontrol_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DebugTriggerMcontrol,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_mcontrol_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mcontrol_specs_3 = {
	sizeof(struct mcontrol),
	offsetof(struct mcontrol, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mcontrol_3 = {
	"mcontrol",
	"mcontrol",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_mcontrol_tags_3,
	sizeof(asn_DEF_mcontrol_tags_3)
		/sizeof(asn_DEF_mcontrol_tags_3[0]) - 1, /* 1 */
	asn_DEF_mcontrol_tags_3,	/* Same as above */
	sizeof(asn_DEF_mcontrol_tags_3)
		/sizeof(asn_DEF_mcontrol_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_mcontrol_3,
	1,	/* Single element */
	&asn_SPC_mcontrol_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mcontrolcompact_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DebugTriggerMcontrolCompact,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_mcontrolcompact_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mcontrolcompact_specs_5 = {
	sizeof(struct mcontrolcompact),
	offsetof(struct mcontrolcompact, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mcontrolcompact_5 = {
	"mcontrolcompact",
	"mcontrolcompact",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_mcontrolcompact_tags_5,
	sizeof(asn_DEF_mcontrolcompact_tags_5)
		/sizeof(asn_DEF_mcontrolcompact_tags_5[0]) - 1, /* 1 */
	asn_DEF_mcontrolcompact_tags_5,	/* Same as above */
	sizeof(asn_DEF_mcontrolcompact_tags_5)
		/sizeof(asn_DEF_mcontrolcompact_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_mcontrolcompact_5,
	1,	/* Single element */
	&asn_SPC_mcontrolcompact_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DebugTrigger_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DebugTrigger, index),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FlexibleRange,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"index"
		},
	{ ATF_POINTER, 2, offsetof(struct DebugTrigger, mcontrol),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_mcontrol_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mcontrol"
		},
	{ ATF_POINTER, 1, offsetof(struct DebugTrigger, mcontrolcompact),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_mcontrolcompact_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mcontrolcompact"
		},
};
static const int asn_MAP_DebugTrigger_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_DebugTrigger_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DebugTrigger_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mcontrol */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* mcontrolcompact */
};
asn_SEQUENCE_specifics_t asn_SPC_DebugTrigger_specs_1 = {
	sizeof(struct DebugTrigger),
	offsetof(struct DebugTrigger, _asn_ctx),
	asn_MAP_DebugTrigger_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_DebugTrigger_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DebugTrigger = {
	"DebugTrigger",
	"DebugTrigger",
	&asn_OP_SEQUENCE,
	asn_DEF_DebugTrigger_tags_1,
	sizeof(asn_DEF_DebugTrigger_tags_1)
		/sizeof(asn_DEF_DebugTrigger_tags_1[0]), /* 1 */
	asn_DEF_DebugTrigger_tags_1,	/* Same as above */
	sizeof(asn_DEF_DebugTrigger_tags_1)
		/sizeof(asn_DEF_DebugTrigger_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DebugTrigger_1,
	3,	/* Elements count */
	&asn_SPC_DebugTrigger_specs_1	/* Additional specs */
};

