/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#ifndef	_Fastint_H_
#define	_Fastint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Fastint */
typedef struct Fastint {
	long	*mmodetimeregaddr	/* OPTIONAL */;
	long	*mmodetimecompregaddr	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Fastint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Fastint;
extern asn_SEQUENCE_specifics_t asn_SPC_Fastint_specs_1;
extern asn_TYPE_member_t asn_MBR_Fastint_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Fastint_H_ */
#include <asn_internal.h>
