/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#ifndef	_FastInterruptModule_H_
#define	_FastInterruptModule_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Range;

/* FastInterruptModule */
typedef struct FastInterruptModule {
	struct index {
		A_SEQUENCE_OF(struct Range) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *index;
	struct connectedHarts {
		A_SEQUENCE_OF(struct Range) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *connectedHarts;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FastInterruptModule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FastInterruptModule;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Range.h"

#endif	/* _FastInterruptModule_H_ */
#include <asn_internal.h>
