/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "PossibleValues.h"

static asn_TYPE_member_t asn_MBR_tuple_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Tuple,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_tuple_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_tuple_specs_2 = {
	sizeof(struct tuple),
	offsetof(struct tuple, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tuple_2 = {
	"tuple",
	"tuple",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_tuple_tags_2,
	sizeof(asn_DEF_tuple_tags_2)
		/sizeof(asn_DEF_tuple_tags_2[0]) - 1, /* 1 */
	asn_DEF_tuple_tags_2,	/* Same as above */
	sizeof(asn_DEF_tuple_tags_2)
		/sizeof(asn_DEF_tuple_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_tuple_2,
	1,	/* Single element */
	&asn_SPC_tuple_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_triple_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Triple,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_triple_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_triple_specs_4 = {
	sizeof(struct triple),
	offsetof(struct triple, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_triple_4 = {
	"triple",
	"triple",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_triple_tags_4,
	sizeof(asn_DEF_triple_tags_4)
		/sizeof(asn_DEF_triple_tags_4[0]) - 1, /* 1 */
	asn_DEF_triple_tags_4,	/* Same as above */
	sizeof(asn_DEF_triple_tags_4)
		/sizeof(asn_DEF_triple_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_triple_4,
	1,	/* Single element */
	&asn_SPC_triple_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PossibleValues_1[] = {
	{ ATF_POINTER, 2, offsetof(struct PossibleValues, tuple),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_tuple_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tuple"
		},
	{ ATF_POINTER, 1, offsetof(struct PossibleValues, triple),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_triple_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"triple"
		},
};
static const int asn_MAP_PossibleValues_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_PossibleValues_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PossibleValues_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tuple */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* triple */
};
static asn_SEQUENCE_specifics_t asn_SPC_PossibleValues_specs_1 = {
	sizeof(struct PossibleValues),
	offsetof(struct PossibleValues, _asn_ctx),
	asn_MAP_PossibleValues_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_PossibleValues_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PossibleValues = {
	"PossibleValues",
	"PossibleValues",
	&asn_OP_SEQUENCE,
	asn_DEF_PossibleValues_tags_1,
	sizeof(asn_DEF_PossibleValues_tags_1)
		/sizeof(asn_DEF_PossibleValues_tags_1[0]), /* 1 */
	asn_DEF_PossibleValues_tags_1,	/* Same as above */
	sizeof(asn_DEF_PossibleValues_tags_1)
		/sizeof(asn_DEF_PossibleValues_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PossibleValues_1,
	2,	/* Elements count */
	&asn_SPC_PossibleValues_specs_1	/* Additional specs */
};

