/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "PrivSatps.h"

asn_TYPE_member_t asn_MBR_PrivSatps_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PrivSatps, sv32),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sv32"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrivSatps, sv39),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sv39"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrivSatps, sv48),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sv48"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrivSatps, sv57),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sv57"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrivSatps, sv64),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sv64"
		},
};
static const ber_tlv_tag_t asn_DEF_PrivSatps_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrivSatps_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sv32 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sv39 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sv48 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sv57 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* sv64 */
};
asn_SEQUENCE_specifics_t asn_SPC_PrivSatps_specs_1 = {
	sizeof(struct PrivSatps),
	offsetof(struct PrivSatps, _asn_ctx),
	asn_MAP_PrivSatps_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PrivSatps = {
	"PrivSatps",
	"PrivSatps",
	&asn_OP_SEQUENCE,
	asn_DEF_PrivSatps_tags_1,
	sizeof(asn_DEF_PrivSatps_tags_1)
		/sizeof(asn_DEF_PrivSatps_tags_1[0]), /* 1 */
	asn_DEF_PrivSatps_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrivSatps_tags_1)
		/sizeof(asn_DEF_PrivSatps_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PrivSatps_1,
	5,	/* Elements count */
	&asn_SPC_PrivSatps_specs_1	/* Additional specs */
};

