/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "Privileged.h"

asn_TYPE_member_t asn_MBR_Privileged_1[] = {
	{ ATF_POINTER, 3, offsetof(struct Privileged, modes),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrivModes,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"modes"
		},
	{ ATF_POINTER, 2, offsetof(struct Privileged, satps),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrivSatps,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"satps"
		},
	{ ATF_POINTER, 1, offsetof(struct Privileged, epmp),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"epmp"
		},
};
static const int asn_MAP_Privileged_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_Privileged_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Privileged_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* modes */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* satps */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* epmp */
};
asn_SEQUENCE_specifics_t asn_SPC_Privileged_specs_1 = {
	sizeof(struct Privileged),
	offsetof(struct Privileged, _asn_ctx),
	asn_MAP_Privileged_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Privileged_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Privileged = {
	"Privileged",
	"Privileged",
	&asn_OP_SEQUENCE,
	asn_DEF_Privileged_tags_1,
	sizeof(asn_DEF_Privileged_tags_1)
		/sizeof(asn_DEF_Privileged_tags_1[0]), /* 1 */
	asn_DEF_Privileged_tags_1,	/* Same as above */
	sizeof(asn_DEF_Privileged_tags_1)
		/sizeof(asn_DEF_Privileged_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Privileged_1,
	3,	/* Elements count */
	&asn_SPC_Privileged_specs_1	/* Additional specs */
};

