/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#ifndef	_PrivSatps_H_
#define	_PrivSatps_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PrivSatps */
typedef struct PrivSatps {
	BOOLEAN_t	 sv32;
	BOOLEAN_t	 sv39;
	BOOLEAN_t	 sv48;
	BOOLEAN_t	 sv57;
	BOOLEAN_t	 sv64;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrivSatps_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivSatps;
extern asn_SEQUENCE_specifics_t asn_SPC_PrivSatps_specs_1;
extern asn_TYPE_member_t asn_MBR_PrivSatps_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _PrivSatps_H_ */
#include <asn_internal.h>
