/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "TraceModule.h"

asn_TYPE_member_t asn_MBR_TraceModule_1[] = {
	{ ATF_POINTER, 3, offsetof(struct TraceModule, branchpredictorentries),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"branchpredictorentries"
		},
	{ ATF_POINTER, 2, offsetof(struct TraceModule, jumptargetcacheentries),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"jumptargetcacheentries"
		},
	{ ATF_POINTER, 1, offsetof(struct TraceModule, contextbuswidth),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contextbuswidth"
		},
};
static const int asn_MAP_TraceModule_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_TraceModule_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TraceModule_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* branchpredictorentries */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* jumptargetcacheentries */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* contextbuswidth */
};
asn_SEQUENCE_specifics_t asn_SPC_TraceModule_specs_1 = {
	sizeof(struct TraceModule),
	offsetof(struct TraceModule, _asn_ctx),
	asn_MAP_TraceModule_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_TraceModule_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TraceModule = {
	"TraceModule",
	"TraceModule",
	&asn_OP_SEQUENCE,
	asn_DEF_TraceModule_tags_1,
	sizeof(asn_DEF_TraceModule_tags_1)
		/sizeof(asn_DEF_TraceModule_tags_1[0]), /* 1 */
	asn_DEF_TraceModule_tags_1,	/* Same as above */
	sizeof(asn_DEF_TraceModule_tags_1)
		/sizeof(asn_DEF_TraceModule_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TraceModule_1,
	3,	/* Elements count */
	&asn_SPC_TraceModule_specs_1	/* Additional specs */
};

