/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Configuration-Structure-Schema"
 * 	found in "../schema.asn"
 * 	`asn1c -Wdebug-lexer -Wdebug-parser -Wdebug-fixer -Wdebug-compiler`
 */

#include "Triple.h"

asn_TYPE_member_t asn_MBR_Triple_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Triple, low),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"low"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Triple, high),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"high"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Triple, mask),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mask"
		},
};
static const ber_tlv_tag_t asn_DEF_Triple_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Triple_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* low */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* high */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* mask */
};
asn_SEQUENCE_specifics_t asn_SPC_Triple_specs_1 = {
	sizeof(struct Triple),
	offsetof(struct Triple, _asn_ctx),
	asn_MAP_Triple_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Triple = {
	"Triple",
	"Triple",
	&asn_OP_SEQUENCE,
	asn_DEF_Triple_tags_1,
	sizeof(asn_DEF_Triple_tags_1)
		/sizeof(asn_DEF_Triple_tags_1[0]), /* 1 */
	asn_DEF_Triple_tags_1,	/* Same as above */
	sizeof(asn_DEF_Triple_tags_1)
		/sizeof(asn_DEF_Triple_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Triple_1,
	3,	/* Elements count */
	&asn_SPC_Triple_specs_1	/* Additional specs */
};

