Configuration-Structure
DEFINITIONS
   AUTOMATIC TAGS ::=
BEGIN
   IMPORTS Debug, DebugModule FROM Debug-Extension
      FlexibleRange, FlexibleRange2, FlexibleRange3, FlexibleRange4, PhysicalAddress,
            Translation FROM Helper-Types
      Isa FROM Hart-Extension
      Zjpm FROM Zjpm-Extension
      Zk   FROM Zk-Extensions
      ;

   CustomOctetString ::= SEQUENCE {
      -- Ideally we'd build something based on information object classes.
      -- asn1tools doesn't support those, however. Some day available tools
      -- might improve. When that day comes we can stop using this type and
      -- use something better.

      -- Vendor-specific ID for this data.
      id INTEGER (0..MAX),
      data OCTET STRING
   }

   Custom ::= SEQUENCE {
      -- Bits 6:0 of the designer/manufacturer’s Identification Code as assigned
      -- by JEDEC Standard JEP106. This is the same value as in mvendorid.Offset.
      jedecOffset INTEGER (0..127),
      -- The count of the number of continuation characters (0x7f) in that same
      -- Identification Code. This is the same value as in mvendorid.Bank.
      jedecBank INTEGER (0..MAX),

      entries SEQUENCE OF CHOICE {
         customOctetString SEQUENCE OF CustomOctetString,
         ...
      }
   }

   Hart ::= SEQUENCE {
      hartid CHOICE { /* 4 choices use 2-bit as the index*/
        hartId4  FlexibleRange2, /* For hart number [1..4] */
        hartId8  FlexibleRange3, /* For hart number [1..8] */
        hartId16 FlexibleRange4, /* For hart number [1..16] */
        hartId   FlexibleRange   /* For hart number > 16 */
      },

      -- Extensions that will not be common on small platforms should go here.
      -- When these extensions are not used they take no space at all.
      extensions SEQUENCE OF CHOICE {
         debug Debug,
         custom SEQUENCE OF Custom,
         zjpm Zjpm,
         zk Zk,
         ...
      } OPTIONAL,

      -- Extensions that will be common on small platforms should go here. When
      -- extensions are actually in use, they take less space in the encoding
      -- this way.
      isa Isa OPTIONAL,
      ...
   }

   -- A wrapper around Top that contains a signature of some kind.
   SignedConfiguration ::= CHOICE {
      -- A PKCS7 DER-encoded SignedData structure. The pcks7-content of this
      -- structure contains a UPER-encoded Top from this schema.
      pkcs7SignedConfiguration OCTET STRING,
      ...
   }

   Top ::= CHOICE {
      -- This wrapper is here in case in the future we want to change to a
      -- different encoding, or in some other way completely overhaul what we're
      -- doing.

      -- In the current schema we always use Configuration or
      -- SignedConfiguration. This choice ends up encoded as 3 bits
      -- (extended:1'h0 index:2'h) followed by the Configuration or
      -- SignedConfiguration itself.
      configuration Configuration,

      signedConfiguration SignedConfiguration,

      -- If we want to change to a different encoding (not ASN.1 UPER) then we
      -- can set this value. The choice ends up encoded as 8 bits (extended:1'h0
      -- index:2'h2 <alternateEncoding>). This simply translates into a
      -- constant byte prefix for potential future alternative encodings.
      alternateEncoding INTEGER (0..31),
      ...
      -- If we want to move to a different kind of Configuration object in the
      -- future, we can put it here, using ASN.1's native extension mechanism.
      -- Encoded as (extended:1'h1 index:5'h0 length:... contents:...)
   }

   ChildStructure ::= SEQUENCE {
      -- Pointer to the physical address (on the host board) where the
      -- Configuration Structure of is accessible.
      structurePointer PhysicalAddress,

      -- How every hart ID mentioned in the child structure should be translated
      -- in order to make sense in the context of this configuration structure.
      hartIdTranslation Translation OPTIONAL,

      -- How every memory address mentioned in the child structure should be
      -- translated in order to make sense in the context of this configuration
      -- structure.
      addressTranslation Translation OPTIONAL,
      ...
   }

   Configuration ::= SEQUENCE {
      harts SEQUENCE OF Hart OPTIONAL,
      debugModule SEQUENCE OF DebugModule OPTIONAL,

      -- If mconfigptr does not point to the root CS, then ancestorPointer must
      -- be used in the CS that mconfigptr does point to, so the parser can find
      -- the root CS.
      ancestorPointer PhysicalAddress OPTIONAL,

      -- Pointers to additional configuration structures that may be present in
      -- this system.
      childPointers SEQUENCE OF ChildStructure OPTIONAL,

      custom SEQUENCE OF Custom OPTIONAL,
      ...
   }
END
