Configuration-Structure
DEFINITIONS
   AUTOMATIC TAGS ::=
BEGIN
   IMPORTS Debug, DebugModule FROM Debug-Extension
      Range, FlexibleRange, FlexibleRange4, FlexibleRange8, FlexibleRange16 FROM Helper-Types
      Tuple, Triple, PossibleValue, PhysicalAddress FROM Helper-Types
      Isa, PrivModes, PrivSatps, Privileged FROM Hart-Extension
      VirtMem FROM Virtual-Memory-Extension
      Zjpm FROM Zjpm-Extension;

   CustomOctetString ::= SEQUENCE {
      -- Ideally we'd build something based on information object classes.
      -- asn1tools doesn't support those, however. Some day available tools
      -- might improve. When that day comes we can stop using this type and
      -- use something better.

      -- Vendor-specific ID for this data.
      id INTEGER (0..MAX),
      data OCTET STRING
   }

   Custom ::= SEQUENCE {
      -- Bits 6:0 of the designer/manufacturer’s Identification Code as assigned
      -- by JEDEC Standard JEP106. This is the same value as in mvendorid.Offset.
      jedecOffset INTEGER (0..127),
      -- The count of the number of continuation characters (0x7f) in that same
      -- Identification Code. This is the same value as in mvendorid.Bank.
      jedecBank INTEGER (0..MAX),

      entries SEQUENCE OF CHOICE {
         customOctetString SEQUENCE OF CustomOctetString,
         ...
      }
   }

   Hart ::= SEQUENCE {
      hartid CHOICE { /* 4 choices use 2-bit as the index*/
        hartId4  FlexibleRange4, /* For hart number [1..4] */
        hartId8  FlexibleRange8, /* For hart number [1..8] */
        hartId16 FlexibleRange16, /* For hart number [1..16] */
        hartId   FlexibleRange   /* For hart number > 16 */
      },
      debug Debug OPTIONAL,
      isa Isa OPTIONAL,
      privileged Privileged OPTIONAL,
      clic Clic OPTIONAL,
      fastInt FastInt OPTIONAL,
      custom SEQUENCE OF Custom OPTIONAL,
      virtmem VirtMem OPTIONAL,
      zjpm Zjpm OPTIONAL,
      ...
   }

   Top ::= CHOICE {
      -- This wrapper is here in case in the future we want to change to a
      -- different encoding, or in some other way completely overhaul what we're
      -- doing.

      -- In the current schema we always use Configuration. This choice ends up
      -- encoded as 2 bits (extended:1'h0 index:1'h0) followed by the
      -- Configuration itself.
      configuration Configuration,

      -- If we want to change to a different encoding (not ASN.1 UPER) then we
      -- can set this value. The choice ends up encoded as 8 bits (extended:1'h0
      -- index:1'h1 <alternateEncoding>). This is simply translates into a
      -- constant byte prefix for potential future alternative encodings.
      alternateEncoding INTEGER (0..63),
      ...
      -- If we want to move to a different kind of Configuration object in the
      -- future, we can put it here, using ASN.1's native extension mechanism.
      -- Encoded as (extended:1'h1 index:5'h0 length:... contents:...)
   }

   Configuration ::= SEQUENCE {
      harts SEQUENCE OF Hart OPTIONAL,
      debugModule SEQUENCE OF DebugModule OPTIONAL,
      traceModule TraceModule OPTIONAL,
      physicalMemory SEQUENCE OF PhysicalMemory OPTIONAL,

      -- Pointers to additional configuration structures that may be present in
      -- this system. This could be used in multi-socket systems where each chip
      -- provides its own configuration description.
      structurePointers SEQUENCE OF PhysicalAddress OPTIONAL,

      custom SEQUENCE OF Custom OPTIONAL,
      ...
   }

   Clic ::= SEQUENCE {
      -- This is a placeholder, which should be filled out with help from the
      -- fast interrupts group. It should probably be moved into the FastInt
      -- section.
      mTimeRegisterAddress INTEGER OPTIONAL,
      mTimeCompareRegisterAddress INTEGER OPTIONAL,
      ...
   }
   TraceModule ::= SEQUENCE {
      -- This is a placeholder, which should be filled out with help from the
      -- trace group.
      branchPredictorEntries INTEGER OPTIONAL,
      jumpTargetCacheEntries INTEGER OPTIONAL,
      contextBusWidth INTEGER OPTIONAL,
      ...
   }
   PhysicalMemory ::= SEQUENCE {
      -- This is a placeholder that might be useful, but there's no obvious task
      -- group who would fill it out.
      address SEQUENCE OF Range,
      cacheable BOOLEAN OPTIONAL,
      lrScSupported BOOLEAN OPTIONAL,
      ...
   }
   FastInt ::= SEQUENCE {
      -- This is a placeholder, which should be filled out with help from the
      -- fast interrupts group.
      mModeTimeRegAddr INTEGER OPTIONAL,
      mModeTimeCompRegAddr INTEGER OPTIONAL,
      ...
   }
END