Helper-Types
DEFINITIONS
   AUTOMATIC TAGS ::=
BEGIN
   EXPORTS FlexibleRange,
           Range, Tuple, Triple, PossibleValues, PhysicalAddress, Translation;

   -- Any size of interger
   Range ::= SEQUENCE {
      start INTEGER (0..MAX),
      length INTEGER (0..MAX)
   }

   -- Any size of flexible range
   FlexibleRange ::= CHOICE {
      -- If this list is empty, the user must assume it contains a single entry
      -- that is 0.
      single SEQUENCE OF INTEGER (0..MAX),
      range SEQUENCE SIZE(1..MAX) OF Range
   }
   -- Value/Mask tuple
   Tuple ::= SEQUENCE {
      value INTEGER,
      mask INTEGER
   }
   -- Low/High with mask applied
   Triple ::= SEQUENCE {
      low INTEGER,
      high INTEGER,
      mask INTEGER
   }
   -- Possible value formats
   PossibleValues ::= SEQUENCE {
      tuple SEQUENCE OF Tuple OPTIONAL,
      triple SEQUENCE OF Triple OPTIONAL,
      ...
   }

   Translation ::= SEQUENCE OF SEQUENCE {
      -- Translate an input value x to an output value y.
      -- If x is in range, y = multiply * x + offset
      -- Otherwise y = x
      range Range,
      offset INTEGER DEFAULT 0,
      multiply INTEGER DEFAULT 1
   }

   -- A physical address, stored with the least-significant byte first.
   -- Any bytes that are not stored are assumed to be 0.
   PhysicalAddress ::= OCTET STRING (SIZE(1..16))
END