== Introduction

"Amidst the RISC-V's diverse extensions arrayed, +
Unified Discovery, a guiding shade. +
Through RV32 and RV64, in ASN.1's embrace, +
It charts the way, processors' nuanced grace. +
No more the quest for elusive lore, +
Unified Discovery, unlocking RISC-V's core."
-- ChatGPT3.5 and Dr. Philipp Tomsich: "An Ode to Unified Discovery" (2024)

Unified Discovery is a low-level discovery mechanism for RISC-V providing discovery of implemented ISA extensions, configuration options and vendor-specific information through a single, extensible mechanism.
It exposes discoverable information both for in-band (hosted) and out-of-band (external debug) use-cases.
The mechanism and the discoverable information are operating-system agnostic: the Unified Discovery message will typically be used to prepare and produce necessary data that is consumed by operating-system specific, higher-level discovery mechanisms.
Applications will typically access a variety of high-level mechanisms (e.g., in Linux use the information from `/proc/cpuinfo` or from the ELF auxiliary vector); a low-level mechanism, such as Unified Discovery, provides the foundation and acts as a source of information.

[NOTE]
====
The current release of Unified Discovery provides discovery for RISC-V ISA extensions only. Discovery for Non-ISA extensions is to be provided in the future.
====

This specification describes Unified Discovery, the RISC-V low-level discovery mechanism, capable of supporting the following use cases:

. Hosted discovery of features by firmware, operating systems and applications
.. Rich operating systems
.. Simple software applications
. Discovery of features by external debug tools
. Out-of-band discovery of features to allow development tools to specialise firmware (e.g. choose the appropriate target flags for compilation and link in the required libraries) for deeply embedded applications

As an example, consider a typical Linux stack:

. Firmware performs system/machine-dependent discovery and populates either a Linux device 
tree or ACPI tables.
. The Linux kernel parses either a Linux device tree or ACPI tables, exposing system 
specifics to userland processes through multiple interfaces:
.. special files in the /proc filesystem
.. device drivers available under /dev
.. files in a mounted sysfs instance
.. flags injected into ELF binaries through the ELF auxiliary vector and accessible 
through getauxval()
.. configuration retrieved through the sysconf() system call
.. information retrievable through the vdso (a virtual DSO mapped by the kernel into each 
processes’ address space)

=== No Central Registry

Unified Discovery is extensible without the need for a central registry of vendor-defined information items.

RISC-V allows the vendor-defined extensibility of the ISA, through vendor-defined extensions that reside in the `custom-opcode` space without any coordination with RISC-V International (as long as no required features are removed and no incompatible features are introduced).
This flexible and decentralized evolution of the RISC-V ISA is reflected in the architecture of Unified Discovery, as it requires minimum coordination between implementators and RISC-V International:

. Based on the published modelling language, encoding rules and the top-level message schema, implementers (both for soft- and hardware) are able to:
.. add proprietary entries in the configuration message, that can safely be identified, read-over (i.e., skipped) or referenced back to the vendor (without a global vendor registry being operated by RISC-V) that specified the proprietary entry format
.. parse any configuration message, including the ability:
... to parse a newer-version message, identifying the new “extensions” and being able to safely skip over them
... to parse a message containing vendor-extensions
. Allow RISC-V to public a machine-readable schema that can enforce the presence of required fields
. Build on international standards and a mature ecosystem

=== Complete Consumption Requirement

A key requirement in any discovery process that avoids a centralized registry is a 
client’s ability to discover that it has read the entire message (including parts that it 
can not understand and skips over) and whether any unparsable extra elements were included 
in the message. This is termed the *Complete Consumption Requirement*.

[NOTE]
=====
The complete consumption requirement is one of the unresolvable issues for CPUID-style instructions that query for values using keys.
=====

=== Integrating message authenticity

While the basic Unified Discovery specification does not mandate message security, the discovery information is wrapped a Cryptographic Message Syntax (RFC5652) envelope to allow for future extensability encompassing message authentication and protection against replay attacks.
Signing the configuration message is supported as an integral (albeit optional) part of the message format.

We expect future extensions to Unified Discovery to make use of this mechanism to enhance security:

. static signing (establishes the integrity and originator of a message)
.. does not protect against replay attacks
.. is supported out-f-the-box and without the need for an additional active component by populating the signerInfos field of the CMS envelope
. dynamic signing (protects against replay-attacks)
.. will require an additional mechanism, in addition to the read-only `mconfigptr` CSR, to issue a challenge to an active component that manages the Unified Discovery message
.. can utilize the CMS envelope to provide a signature of the Unified Discovery data _and_ of a signed-attribute that contains a response derived from the challenge

