== Guidelines on Mapping from Discoverable Elements to ASN.1

This section describes common patterns when expressing hardware configuration using the 
schema.

Each hart's mconfigptr CSR contains an address to a discovery data. The discovery data is 
a binary encoded instance of the ASN.1 Sequence named `DiscoveryData`. The 

`DiscoveryData` Sequence consists of a version number which indicates the version of the 
schema, followed by a list of extensionis, each of which represents an extension and its 
associated configuration. All elements in this list are optional to allow extremely 
flexible combinations. The list of extensions is followed by an optional errata and any 
arbitrary discovery data that is vendor-specific.


The elements in the list of extensions are of different types according to the nature of the 
extensions. For most extensions that do not come with any configurable parameters, the 
type of the element is simply an empty ASN.1 Sequence, i.e. `SEQUENCE {}`. For extensions 
that do provide configurable hardware parameters, a specific type for that extension is 
defined to capture the parameters and allowed values of the parameters. For example, the 

vector extension allows various `VLEN` values, thus, a `RVVConfig` type is provided. The 
`RVVConfig` type is a sequence that consists of one element called `vlen` that is a `BIT 
STRING` ASN.1 type that allows a few options.

=== Extensibility, Versioning & “Container Format”

The `DiscoveryData` is an extensible type. This means additional elements can be inserted
after the `version` element and also after the  list of extensions. This allows newly defined
but potentially not-yet-ratified extensions to exist in various circumstances such as prototyping.

The version of the schema is via the `version` of the schema. Future releases of the 
schema will contain a new value for this element.

The `DiscoveryAdditionalData` type is provided as a container format for a  
vendor specific binary blob to be included. This element is optional. The `tag` element 
provides a unique identifier for the encoded string. The `payload` element contains the 
encoded binary blob.

=== Supported subset of X.680

RISC-V Unified Discovery provides support for the following subset of elementary types defined by X.680 (02/2021 edition):

. `BOOLEAN`, as specified in clause 18
. `INTEGER`, as specified in clause 19
. `ENUMERATED`, as specified in clause 20
. `BIT STRING`, as specified in clause 22
. `OCTET STRING`, as specified in clause 23
. `SEQUENCE`, as specified in clause 25
. `SEQUENCE OF`, as specified in clause 26
. `CHOICE`, as specified in clause 29
. `OBJECT IDENTIFIER`, as specified in clause 32
. `UTF8String`, as specified in clauses 40 and subclause 41.16
. `UTCTime` (Universal Time), as specified in clause 47

For the above subset of elementary types, the subtype element specifications of clause 51 are supported as part of the RISC-V Unified Discovery specifications.

Extension markers, as specified in clause 52, are supported as part of the RISC-V Unified Discovery specification.

=== What types of discoverable elements do we support?

The Unified Discovery Specification supports the following elements to be expressed.

==== Existence

Existence manifests as an empty ASN.1 Sequence.

==== Structural elements (lists, arrays)

Lists and arrays manifest as ASN.1 Sequences.

==== Parameters (enums, integer ranges, addresses)

Parameters manifests as named value of the elements of a type.

=== How to map these to ASN.1

== Encoding rules

=== Reference back to X.69x ?
