== Solution Outline

// . Schema + Value Notation (human readable form) + Parser

// . Reuse existing standards -> ITU standards & examples (SNMP)

The Unified Discovery Specification provides a ASN.1 (see ITU-T X.680 and ISO/IEC 
8824) based schema (referred to as 'the schema' hereafter) for vendors to express the 
      presence of RISC-V architectural extensions and configuration options of the 
extensions. The schema uses a subset of ASN.1 elements to define extensible data types.  
The vendors are expected to declare an instance of the configuration data type that
 describes the hardware. The vendors' declaration lives in a description file.

The schema and the description files are parsed by any ASN.1 parser which produces a 
binary blob, referred to as 'the discovery data' hereafter. The discovery data is 
distributed with hardware. At boot time, the firmware reads the discovery data and decodes 
it into hand-over structures for subsequent boot stages. It also allows out-of-band use 
case as defined above.

This specification provides encoding recommendations for generating the discovery data.

//. vendor-specific info

=== The Unified Discovery Schema

The Unified Discovery Schema allows vendors to declare both RISC-V standard extensions and 
arbitrary vendor-specific platform-dependent data. For the latter, it facilitates 
the inclusion of
any custom extensions that may be present in the hardware. This option eliminates the 
interaction for including custom extensions in specific instances of the discovery data 
between each vendor and RISC-V International.

Specifically, the schema's discovery data type provides room for arbitrary binary encoded 
data to be included in the discovery data. Each vendor can encode any specific data in any 
desirable encoding scheme and include the encoding result into the discovery data.

For such data to be successfully used on the hardware, the vendors including such data are 
responsible for providing any decoding facility, e.g. boot loader code, for the purpose of 
decoding the vendor specific data.

NOTE: The schema and the discovery data are static data structures in the sense that no 
attempt to dynamically enumerate hardware resource is performed. For example, for devices 
on a hot-pluggable bus such as USB, it is up to the subsequent boot sequences, if needed, 
to enumerate the devices and add to the handover structure, such as a device tree, 
expected by the next boot stage after the boot loader.

This specification provides a schema of the data structure that is generic and extensible.  
See <<_asn_1_schema>> for the schema. Vendor-specific data can be included without 
hindering the successful parsing of the configuration.

=== The Discovery Data

The discovery data is made available to software within the physical address space of the 
hardware. The par-hart mconfigptr CSR contains the physical address.
The base-address of the binary-encoded representation is accessible through the single 
CSR, i.e. the mconfigptr CSR.  No other ISA considerations, beyond the provision of an 
additional CSR are required.

The discovery data encoded uses standardized encoding rules (see ITU-T X.690 and ISO 
8825).  For in-memory representations, the unaligned packed encoding rules (unaligned PER, 
see ITU-T X.691) are used. The configuration data can (optionally) be cryptographically 
signed.

Target software (usually firmware) that performs discovery will read the uPER-encoded 
message to retrieve the relevant configuration elements. The message can be decoded either 
using a stream parser with small memory footprint (i.e. the parser reads from the 
beginning until it retrieves the requested data element) or can be converted 
start-to-finish into a firmware-specific data structure. Given the compact representation 
and the low memory requirements for parsers, a uPER message can be efficiently parsed even 
during the startup of a deeply embedded microcontroller application (even though we 
envision out-of-band discovery and specialization for deeply embedded and 
resource-constrained use-cases).

=== Summary

The unified discovery mechanism for RISC-V builds on the following technology stack:

. ASN.1 (X.680) for modelling the data structures, independent of their encoding

. Packed Encoding Rules (X.691) for the binary encoding of data structures (in-band)

. XML Encoding Rules (X.693) for the XML encoding of data structures (out-of-band)

. RISC-V International specific guidelines to allow the efficient aggregation of RISC-V 
global and vendor-specific data elements without a central registration authority

. RISC-V International specific guidelines for the encoding of detached signatures 
(PKCS#7/CMS) using Packed Encoding Rules


NOTE: The benefits of using X.680 and X.693 over vendor-specific (e.g. Google Protobuf, 
Apache Avro etc.) marshalling frameworks are the fact that these are international 
standards, widespread adoption and availability of open-source and commercial codec 
libraries.

=== Software Usage

Retrieval and decoding of the configuration structure can happen in any of the following 
scenarios:

- Software (in-band)

Firmware will access the CSR and read the configuration message to extract the device’s 
configuration as part of its discovery process. The implementation details of this process 
(e.g., whether firmware initiates a read from the top and searches for individual tags, or 
if firmware converts the entire discovery information into an in-memory representation at 
once) are left to device implementers.

- External debug (in-band)

External debug will retrieve the CSR and then read out (once) the referenced memory region 
to retrieve the configuration information for a specific target device. The retrieved 
configuration message is then parsed by the external debugger to determine the 
configuration, features and capabilities of the device.

- Software development environment (out-of-band)

For (deeply) embedded applications, firmware will be specialised to target the specific 
target device only by pushing the discovery and configuration to the software development 
environment. These cases can be efficiently supported either by reading the configuration 
structure from a target device using an external debugger, or by retrieving a 
configuration structure from the manufacturer’s website.

[NOTE]
====
It is possible to incorporate Unified Discovery into the product development process in 
the following manner. This example assumes U-boot is adopted as the bootloader on the 
product.

. Some vendor feeds certain ASN.1 value declaration for a product to certain ASN.1 
   compilation tools. 
. The ASN.1 compilation tools generate the encoded binary blob of the ASN.1 value 
   declaration, and generate necessary C headers and functions to aid decoding of the 
blob.
. The vendor integrates the C headers and functions into U-boot. For the vendor-specific 
   portion (see <<_container_format>>), special routines are also provided.
. The vendor distribute the binary blob together with U-boot.
====
