name: Pylint
on: pull_request
jobs:
    Test-Examples:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install asn1tools deepdiff
            - run: sudo apt install pylint
            - run: make pylint
